### ISSUE TITLE
Boot Loop - Firmware 1.3 - 2024.6.1

### ISSUE THREAD

**Issue by chrisblach** [exico91/SommerESP#4]
I seem to be getting a boot loop on the SommerESP v1.1 control board. It has a ESP32-C3. I flashed it with the base image Firmware 1.3 - 2024.6.1. 

Loops this message:
```
[11:33:47]ESP-ROM:esp32c3-api1-20210207
[11:33:47]Build:Feb  7 2021
[11:33:47]rst:0xf (BROWNOUT_RST),boot:0xd (SPI_FAST_FLASH_BOOT)
[11:33:47]SPIWP:0xee
[11:33:47]mode:DIO, clock div:1
[11:33:47]load:0x3fcd6100,len:0x438
[11:33:47]load:0x403ce000,len:0x918
[11:33:47]load:0x403d0000,len:0x24e4
[11:33:47]entry 0x403ce000
```

Is this to be expected without connecting to the Sommer board?

**Comment by exico91** [comment]
Hello,

Yes, unfortunately with some serial adapters it boot loops at 3.3v because the adapter cannot supply enough current. 
Its a hit or miss, I have two and one does this and the other not.
You can bypass the problem by supplying 5V to the power board and the serial connection to the control board instead of supplying directly the control board with the 3.3v on the header. Usually 5v comes "unfiltered" from the USB supply and it is enough current. The power board supports input voltages from 4.5V to 40V

![2024_11_04_21_13_21_Visualizzatore_3D](https://github.com/user-attachments/assets/b058c5b9-af2a-497c-8287-24745917a288)

**Comment by chrisblach** [comment]
Thanks @exico91 , this was the exact problem! I changed the ping to the 5V on my programmer and was able to successfully flash the esp32. After flashing, the device was seen on my wifi and after plugging it into the Sommer unit it worked liked a charm!! Great project, I appreciate your efforts.

Do you think we can add some documentation about this or would this issue history be enough?
